metacoin/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('option.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

option/urls.py
from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import TemplateView

from .sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('', views.homee, name='homepage'),
    path('contact', views.contact, name='contact'),
    path('test', views.test, name='testpage'),
    path('ourteam', views.ourteam, name='ourteam'),
    path('awards', views.awards, name='awards'),
    path('segregated', views.segregated, name='segregated'),
    path('disclosure', views.disclosure, name='disclosure'),
    path('terms', views.terms, name='terms'),
    path('policy', views.policy, name='policy'),
    path('laundering', views.laundering, name='laundering'),
    path('audit', views.audit, name='audit'),
    path('trade_risk', views.trade_risk, name='trade_risk'),
    path('bonus', views.bonus, name='bonus'),
    path('forex_essentials', views.forex_essentials, name='forex_essentials'),
    path('exchange_rates', views.exchange_rates, name='exchange_rates'),
    path('analysis', views.analysis, name='analysis'),
    path('technical_analysis', views.technical_analysis, name='technical_analysis'),
    path('forex', views.forex, name='forex'),
    path('precious_metals', views.precious_metals, name='precious_metals'),
    path('cfd_shares', views.cfd_shares, name='cfd_shares'),
    path('cfd_indices', views.cfd_indices, name='cfd_indices'),
    path('cfd_crypto', views.cfd_crypto, name='cfd_crypto'),
    path('leverage', views.leverage, name='leverage'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'), #sitemap
    path("robots.txt",TemplateView.as_view(template_name="zloggr/robots.txt", content_type="text/plain")),  #robots.txt file
]

members/models.py
from django.db import models
from django.contrib.auth.models import User 
from .countries import COUNTRIES
from .account_type import ACCOUNT_TYPE
from .accountStatus import ACCOUNT_STATUS

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    phoneNumber = models.CharField(max_length=16, null=True)
    country = models.CharField(max_length=300, null=True, choices=COUNTRIES)
    accountType = models.CharField(max_length=300, null=True, choices=ACCOUNT_TYPE)
    accountStatus = models.CharField(max_length=300, null=False, choices=ACCOUNT_STATUS, default='NV') 
    deposit = models.CharField(max_length=15, null=False, default=0)
    balance = models.CharField(max_length=15, null=False, default=0.00)
    available = models.CharField(max_length=15, null=False, default=0.00)
    joined = models.DateField(auto_now_add=True)


    def __str__(self):
        if not self.user:
            return "Anonymous"
        return self.user.username

templates/authenticate/bitcoin.html
{% extends 'authenticate/base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <div class="container-fluid lefft">
        <div class="card-top">
            <div class="d-flex justify-content-between">
                <span>Welcome Back, <strong>{{ request.user.first_name }} {{ request.user.last_name }}</strong></span>
                <span>User / <strong>Fund Account</strong></span>
                <hr>
            </div>
            <div class="">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="alert alert-primary" role="alert">
                            <span class="reeed">Notice!</span>

                             <br>

                            Please Note that Minimum Fund Amount is $500. Contact payments@metacoinoptions.com for a more detailed description. Ensure to provide your Funding Code when contacting support. If you encounter any issue while funding your account, please contact payments@metacoinoptions.com for assistance.

                            Your account will be credited once your payment is confirmed.

                        </div>
                    </div>  
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12">
                        <p class="text-center"><i class="fa fa-university" aria-hidden="true"></i> Pay with bitcoin</p>
                        <hr>
                    </div>
                    <div class="col-lg-4 px-5 pb-3">
                        <div class="px-5">
                            <img src="{% static 'pictures/bitcoin.png' %}" class="d-block w-100" alt="...">
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="alert alert-primary" role="alert">
                            <span>Crypto Funding is Instant</span>

                            <br>

                            Your account will be credited once your payment is confirmed.
                            NOTE: If you have problems finding your Transaction Hash ID, Use the last 10 digits of your wallet address as the Transaction Hash ID.
                            If you encounter any issue while funding your account, please contact payments@metacoinoptions.com for assistance. 

                        </div>
                        <form>
                            <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Username</label>
                                <input type="text" class="form-control" id="formControlReadonly" aria-label="readonly input example" readonly placeholder="{{ request.user.username }}">
                            </div>
                            <label for="amount" class="form-label">Amount</label>
                            <div class="input-group mb-3">
                                <span class="input-group-text">$</span>
                                <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)" id="amount" placeholder="Enter Amount">
                                <span class="input-group-text">.00</span>
                            </div>
                            <label for="amount" class="form-label">Send Payments To:</label>
                            <div class="form-outline">
                                <input
                                    class="form-control"
                                    id="formControlReadonly"
                                    type="text"
                                    placeholder="1GoAjdkcrfnHRv4GeSekDNoLN6BZbWZePd"
                                    aria-label="readonly input example"
                                    readonly
                                />
                            </div>
                            <br>
                            <label for="amount" class="form-label">OR SCAN TO COPY:</label>
                            <div class="container">
                                <div class="row">
                                    <div class="col-12 d-flex d-none d-xl-block d-xxl-none">
                                        <img src="{% static 'pictures/QR code.jpeg' %}">
                                    </div>
                                    <div class="col-12 d-flex d-xl-none d-xxl-block">
                                        <img src="{% static 'pictures/QR code-sm.jpeg' %}">
                                    </div>
                                </div>
                            </div>
                            
                            <div class="form-outline">
                                <br>
                                <label for="amount" class="form-label">Senders Wallet Address:</label>
                                <input type="text" id="typeText" class="form-control" placeholder="Enter your Wallet Address" />
                            </div>
                            <div class="form-outline">
                                <br>
                                <label for="amount" class="form-label">Transaction HASH ID:</label>
                                <input type="text" id="typeText" class="form-control" placeholder="Enter Transaction HASH ID" />
                            </div>
                            <div class="mb-3">
                                <br>
                                <label for="exampleFormControlTextarea1" class="form-label">Description.</label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="2" placeholder="Enter description (Optional)"></textarea>
                            </div>
                            <div class="d-grid gap-2 col-6 mx-auto">
                                <button class="btn btn-success" type="button">Fund</button>
                            </div>
                        </form>
                    </div>  
                </div>
            </div>
        </div>
         
    </div>
</div>

{% endblock %}

templates/authenticate/copy.html
{% extends 'authenticate/base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <div class="container-fluid lefft">
        <div class="card-top">
            <div class="d-flex justify-content-between">
                <span>Welcome Back, <strong>{{ request.user.first_name }} {{ request.user.last_name }}</strong></span>
                <span>User / <strong>Fund Account</strong></span>
                <hr>
            </div>
            <div class="">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="alert alert-primary" role="alert">
                            <span class="reeed">Notice!</span>

                             <br>

                            Please Note that Minimum Fund Amount is $500. Contact payments@metacoinoptions.com for a more detailed description. Ensure to provide your Funding Code when contacting support. If you encounter any issue while funding your account, please contact payments@metacoinoptions.com for assistance.

                            Your account will be credited once your payment is confirmed.

                        </div>
                    </div>  
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12">
                        <p>Pay with Bitcoin</p>
                        <hr>
                        <div class="alert alert-primary" role="alert">
                            <span>Bitcoin Funding is Instant</span>

                            <br>

                            Your account will be credited once your payment is confirmed.
                            NOTE: If you have problems finding your Transaction Hash ID, Use the last 10 digits of your wallet address as the Transaction Hash ID.
                            If you encounter any issue while funding your account, please contact payments@metacoinoptions.com for assistance. 

                        </div>
                        <form>
                            <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Username</label>
                                <input type="text" class="form-control" id="formControlReadonly" aria-label="readonly input example" readonly placeholder="{{ request.user.username }}">
                            </div>
                            <label for="amount" class="form-label">Amount</label>
                            <div class="input-group mb-3">
                                <span class="input-group-text">$</span>
                                <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)" id="amount" placeholder="Enter Amount">
                                <span class="input-group-text">.00</span>
                            </div>
                            <label for="amount" class="form-label">Send Payments To:</label>
                            <div class="form-outline">
                                <input
                                    class="form-control"
                                    id="formControlReadonly"
                                    type="text"
                                    placeholder="1GoAjdkcrfnHRv4GeSekDNoLN6BZbWZePd"
                                    aria-label="readonly input example"
                                    readonly
                                />
                            </div>
                            <br>
                            <label for="amount" class="form-label">OR SCAN TO COPY:</label>
                            <div class="container">
                                <div class="row">
                                    <div class="col-12 d-flex d-none d-xl-block d-xxl-none">
                                        <img src="{% static 'pictures/QR code.jpeg' %}">
                                    </div>
                                    <div class="col-12 d-flex d-xl-none d-xxl-block">
                                        <img src="{% static 'pictures/QR code-sm.jpeg' %}">
                                    </div>
                                </div>
                            </div>
                            
                            <div class="form-outline">
                                <br>
                                <label for="amount" class="form-label">Senders Wallet Address:</label>
                                <input type="text" id="typeText" class="form-control" placeholder="Enter your Wallet Address" />
                            </div>
                            <div class="form-outline">
                                <br>
                                <label for="amount" class="form-label">Transaction HASH ID:</label>
                                <input type="text" id="typeText" class="form-control" placeholder="Enter Transaction HASH ID" />
                            </div>
                            <div class="mb-3">
                                <br>
                                <label for="exampleFormControlTextarea1" class="form-label">Description.</label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="2" placeholder="Enter description (Optional)"></textarea>
                            </div>
                            <div class="d-grid gap-2 col-6 mx-auto">
                                <button class="btn btn-success" type="button">Fund</button>
                            </div>
                        </form>
                    </div>  
                </div>
            </div>
        </div>
         <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12">
                        <p class="text-center">FAQ</p>
                        <hr>
                        <!-- ======= Profile Section ======= -->
                        <section id="profile" class="profile">
                            <div class="container" data-aos="fade-up">
                                <p>
                                    <div class="d-grid gap-2">
                                        <button class="btn btn-primary btn-lg" style="background-color: #131722;" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample1" aria-expanded="false" aria-controls="collapseExample">
                                            Why Bitcoin?
                                        </button>
                                    </div>
                                </p>
                                <div class="collapse" id="collapseExample1">
                                    <div class="card card-body">
                                        <p>Bitcoin is the fastest way to fund accounts.</P>
                                    </div>
                                </div>

                                <p>
                                    <div class="d-grid gap-2">
                                        <button class="btn btn-primary btn-lg" style="background-color: #131722;" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample2" aria-expanded="false" aria-controls="collapseExample">
                                        How long do I wait before my investment start counting?
                                        </button>
                                    </div>
                                </p>
                                <div class="collapse" id="collapseExample2">
                                    <div class="card card-body">
                                        <p>Once your fund is confirmed, your investment starts counting.</p>
                                    </div>
                                </div>

                                <p>
                                    <div class="d-grid gap-2">
                                        <button class="btn btn-primary btn-lg" style="background-color: #131722;" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample3" aria-expanded="false" aria-controls="collapseExample">
                                        What happens to a failed fund transaction?
                                        </button>
                                    </div>
                                </p>
                                <div class="collapse" id="collapseExample3">
                                    <div class="card card-body">
                                        <p>This is rare but we will help sort out any failed transaction. </p>
                                    </div>
                                </div>
                            </div>
                        </section><!-- End Services Section -->
                    </div>
                </div>
            </div>
        </div>
         <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12">
                        <p>Latest Deposits</p>
                        <hr>
                    </div>
                    <div class="container-fluid">
                        <div class="col-lg-12 d-flex justify-content-between">
                            <div>
                                <p>Fund Amount</p>
                            </div>
                            <div>
                                <p>Fund Code</p>
                            </div>
                            <div>
                                <p>Date</p>
                            </div>
                            <div>
                                <p>Description</p>
                            </div>
                            <div>
                                <p>Status</p>
                            </div>
                        </div>
                        <div class="form-outline">
                            <input
                                class="form-control"
                                id="formControlReadonly"
                                type="text"
                                placeholder="No data available in table"
                                aria-label="readonly input example"
                                readonly
                            />
                            <br>
                        </div>
                        <div class="col-lg-12 d-flex justify-content-between">
                            <div>
                                <p>Fund Amount</p>
                            </div>
                            <div>
                                <p>Fund Code</p>
                            </div>
                            <div>
                                <p>Date</p>
                            </div>
                            <div>
                                <p>Description</p>
                            </div>
                            <div>
                                <p>Action</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/authenticate/ethereum.html
{% extends 'authenticate/base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <div class="container-fluid lefft">
        <div class="card-top">
            <div class="d-flex justify-content-between">
                <span>Welcome Back, <strong>{{ request.user.first_name }} {{ request.user.last_name }}</strong></span>
                <span>User / <strong>Fund Account</strong></span>
                <hr>
            </div>
            <div class="">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="alert alert-primary" role="alert">
                            <span class="reeed">Notice!</span>

                             <br>

                            Please Note that Minimum Fund Amount is $500. Contact payments@metacoinoptions.com for a more detailed description. Ensure to provide your Funding Code when contacting support. If you encounter any issue while funding your account, please contact payments@metacoinoptions.com for assistance.

                            Your account will be credited once your payment is confirmed.

                        </div>
                    </div>  
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12">
                        <p class="text-center"><i class="fa fa-university" aria-hidden="true"></i> Pay with ethereum</p>
                        <hr>
                    </div>
                    <div class="col-lg-4 px-5 pb-3">
                        <div class="px-5">
                            <img src="{% static 'pictures/ethereum.png' %}" class="d-block w-100" alt="...">
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="alert alert-primary" role="alert">
                            <span>Crypto Funding is Instant</span>

                            <br>

                            Your account will be credited once your payment is confirmed.
                            NOTE: If you have problems finding your Transaction Hash ID, Use the last 10 digits of your wallet address as the Transaction Hash ID.
                            If you encounter any issue while funding your account, please contact payments@metacoinoptions.com for assistance. 

                        </div>
                        <form>
                            <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Username</label>
                                <input type="text" class="form-control" id="formControlReadonly" aria-label="readonly input example" readonly placeholder="{{ request.user.username }}">
                            </div>
                            <label for="amount" class="form-label">Amount</label>
                            <div class="input-group mb-3">
                                <span class="input-group-text">$</span>
                                <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)" id="amount" placeholder="Enter Amount">
                                <span class="input-group-text">.00</span>
                            </div>
                            <label for="amount" class="form-label">Send Payments To:</label>
                            <div class="form-outline">
                                <input
                                    class="form-control"
                                    id="formControlReadonly"
                                    type="text"
                                    placeholder="0x8a038aab834ca3215607af61e40b25dcfe66b39c"
                                    aria-label="readonly input example"
                                    readonly
                                />
                            </div>
                            <br>
                            <label for="amount" class="form-label">OR SCAN TO COPY:</label>
                            <div class="container">
                                <div class="row">
                                    <div class="col-12 d-flex d-none d-xl-block d-xxl-none">
                                        <img src="{% static 'pictures/ethbarcode.jpeg' %}">
                                    </div>
                                    <div class="col-12 d-flex d-xl-none d-xxl-block">
                                        <img src="{% static 'pictures/ethbarcode-sm.jpg' %}">
                                    </div>
                                </div>
                            </div>
                            
                            <div class="form-outline">
                                <br>
                                <label for="amount" class="form-label">Senders Wallet Address:</label>
                                <input type="text" id="typeText" class="form-control" placeholder="Enter your Wallet Address" />
                            </div>
                            <div class="form-outline">
                                <br>
                                <label for="amount" class="form-label">Transaction HASH ID:</label>
                                <input type="text" id="typeText" class="form-control" placeholder="Enter Transaction HASH ID" />
                            </div>
                            <div class="mb-3">
                                <br>
                                <label for="exampleFormControlTextarea1" class="form-label">Description.</label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="2" placeholder="Enter description (Optional)"></textarea>
                            </div>
                            <div class="d-grid gap-2 col-6 mx-auto">
                                <button class="btn btn-success" type="button">Fund</button>
                            </div>
                        </form>
                    </div>  
                </div>
            </div>
        </div>
         
    </div>
</div>

{% endblock %}

templates/authenticate/profile.html
{% extends 'authenticate/base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <div class="container-fluid lefft">
        <div class="card-top">
            <div class="d-flex justify-content-between">
                <span>Welcome Back, <strong>{{ request.user.first_name }} {{ request.user.last_name }}</strong></span>
                <span>User / <strong>Profile</strong></span>
                <hr>
            </div>
        </div>

        <div class="card col-lg-12">
            <div class="card-body">
                
                
                <i class="fa fa-tachometer" aria-hidden="true">  Overview</i>
              
                
            </div>
        </div>


        <div class="row">
            <div class="card col-lg-6">
                <div class="card-body profile-card">
                    <h2 class="card-title wallet"><b>Personal Details</b></h2>
                    <hr>
                    <div class="row">
                        <div class="col-lg-2">
                            <img src="{% static 'pictures/user.png' %}" width="80" height="80">
                        </div>
                        <div class="col-lg-10">
                            <div class="d-flex flex-column bd-highlight mb-3">
                                <div class="p-0 bd-highlight">Hello</div>
                                <div class="p-0 bd-highlight"><h4><strong>{{ request.user.first_name }} {{ request.user.last_name }}</strong></h4></div>
                                <div class="p-0 bd-highlight"><i class="fa fa-phone" aria-hidden="true"> +{{ user.profile.phoneNumber }}</i></div>
                                <div class="p-0 bd-highlight"><i class="fa fa-envelope" aria-hidden="true"> {{ request.user.email }}</i></div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="col-lg-12">
                        <div class="d-flex flex-column bd-highlight mb-3">
                            <div class="p-0 bd-highlight"><span><b>Country:</b> {{ user.profile.get_country_display }}</span></div>
                            <div class="p-0 bd-highlight"><b>Account Status:</b> {{ user.profile.get_accountStatus_display }}</div>
                            <div class="p-0 bd-highlight"><b>Account Type:</b> {{ user.profile.accountType }}</div>
                            <div class="p-0 bd-highlight"><b>Joined on:</b> {{ user.profile.get_joined_display }}</div>

                        </div>  
                    </div>
                </div>
            </div>


            <div class="card col-lg-6">
                <div class="card-body">
                    <h3 class="card-title wallet"><b>Wallet</b></h3>
                    <hr>
                    <h6><b>Available Balance</b></h6>
                    <h6 class="wallet greeen"><b>$ {{ user.profile.available }}</b></h6>

                    <div class="d-flex justify-content-between">
                        <h7>Invested<p class="bluee">0 $</p></h7>
                         
                        <h7>Bitcoin Balance<p class="bluee">{{ user.profile.balance }}</p></h7>
                        
                    </div>

                    <div class="d-flex justify-content-between">

                        <h7>Total Withdrawn<p class="bluee">0</p></h7>
                             

                        <h7>Total Deposit<p class="bluee">{{ user.profile.deposit }}</p></h7>
                    </div>
                            
                    <div class="d-flex justify-content-between">

                        <h7>Referral Bonus<p class="bluee">0 $</p></h7>
                             
                        <h7>Account Status<p class="bluee">{{ user.profile.get_accountStatus_display }}</p></h7>
                            
                    </div>
                    <div class="d-flex justify-content-start">

                        <h7>Account Type<p class="bluee">{{ user.profile.accountType }}</p></h7>

                    </div>
                    <div class="d-flex justify-content-between">

                        <a href="#" class="btn btn-success">Fund Account</a>

                        <a href="#" class="btn btn-danger">Withdraw Funds</a> 

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}